### ISSUE TITLE
Swag documentation's list of supported dns providers is outdated

### ISSUE THREAD

**Issue by Solsmed** [linuxserver/docker-documentation#117]
The SWAG documentation page has one paragraph listing [dns-provider plugins](https://github.com/linuxserver/docker-documentation/blob/master/general/swag.md#create-container-via-dns-validation-with-a-wildcard-cert), but the list is outdated in relation to what providers are [actually possible to use](https://github.com/linuxserver/docker-swag/tree/master/root/defaults/dns-conf).

The paragraph could for example be reworded to end with "..., and many others (see [docker-swag repo](https://github.com/linuxserver/docker-swag/tree/master/root/defaults/dns-conf) for an up to date list)"

**Comment by aptalca** [comment]
fixed in #118
