### ISSUE TITLE
Document / support mongodb replicaset mode for unifi-network-application

### ISSUE THREAD

**Issue by rdmcguire** [linuxserver/docker-documentation#176]
I would like to use an existing mongodb replicaset running in kubernetes, is there an existing method for connecting to a mongo replicaset or would this be new feature? Thank you for all the work that goes in to maintaining this container image!

**Comment by thespad** [comment]
It's not something any of us have tested; whether it's supported or not is a matter for Ubiquiti.

If there's anything that needs altering about the image to support it we can take a look, but it's likely just a matter of making the necessary adjustments to the server.properties connection details.

**Comment by Roxedus** [comment]
Closing, not the correct repo.
