### ISSUE TITLE
Linuxserver version doesn't work with ntfy

### ISSUE THREAD

**Issue by xyitest2** [linuxserver/docker-documentation#240]
When issuing command:
curl -X POST \
    -F "body=Test Message" \
    -F "tags=all" \
    http://apprise.home:8000/notify/apprise

I got: "Bad attachment". Similar using web interface. Without changes in configuration it used to work some time ago.

When I pulled original image and used the same ntfy config/endpoint it works well.

**Comment by j0nnymoe** [comment]
This is not the correct place to get support, please read https://docs.linuxserver.io/general/how-to-get-support/

**Comment by xyitest2** [comment]
You are right. One of the links was misleading most probably. Anyway - please feel free to reroute in the right direction. This is your product having the fault. I'm good after switching to original docker image.

**Comment by Roxedus** [comment]
I am very curious to what link lead you to this repository, the general link top right?

The thing you are running into is documented also on relevant page in this repository, it calls out attachments.

**Comment by xyitest2** [comment]
Not sure how I got there. It could be me - I'm not heavy github user. If there will be no more issues like this, I guess you can forget the case.
If the problem I described is already addressed that's great, I will switch back to your repo after some time.
Appreciate your work guys, it helped me to start with docker. Cheers.
