### ISSUE TITLE
Incorrect usage of "then" for comparison

### ISSUE THREAD

**Issue by lwsrbrts** [linuxserver/docker-documentation#275]
The following line uses `then` as a comparison, which is incorrect.

https://github.com/linuxserver/docker-documentation/blame/0248b7d8b80412405b5983ef0459b3fdc9c2d266/docs/images/docker-apprise-api.md#L21

Additionally, the use of the `+` sign after the number is redundant, since you've already said "more than".

The sentence should be:

`Send notifications to more than 65 services.`

**Comment by thespad** [comment]
The blurb was taken verbatim from the upstream project: https://github.com/caronc/apprise-api/commit/e91a2aee55b38ca78abd51173dd71246ecf8a749

I'll update it to reflect the current wording when I have the chance.
