### ISSUE TITLE
Error after Migration starts

### ISSUE THREAD

**Issue by KhawZhenXuan** [linuxserver/docker-documentation#280]
Every time when it starts to migrate, it will have a lot of errors and sometimes crashes.
Specs:
Calibre running on Synology DS423+ Container Manager (Not Docker)

Calibre Container Log: https://replit.com/@KHAW-ZHEN-XUANZ/Calibre-Error-Log (Its HTML code, save it as a file to see, no choice, sorry)

**Comment by aptalca** [comment]
This is not the correct repo
