### ISSUE TITLE
Inconsistent use of PUID and PGID in environment section of docker-compose

### ISSUE THREAD

**Issue by ZenithDK** [linuxserver/docker-documentation#6]
"[Understanding PUID and PGID](https://docs.linuxserver.io/general/understanding-puid-and-pgid)" describes it as:
`environment:
  PUID: 1000
  PGID: 1000`
Whereas all [other pages ](https://docs.linuxserver.io/images/docker-nzbget)I checked describes it as:
`environment:
  - PUID=1000
  - PGID=1000`
There's the = vs : and the starting dash.
The second is the correct use I have found.

**Comment by aptalca** [comment]
Yup, that's an error. I'll update these docs soon and will fix it then.

Thanks for letting us know

**Comment by JoshStark** [comment]
This has been rectified in the documentation: https://docs.linuxserver.io/general/understanding-puid-and-pgid
